spring:
  ai:
    openai:
      api-key: ${LLM_API_KEY:test_key}
  application:
    name: intent-recognizer
  datasource:
    password: ${DATABASE_PASSWORD:postgres}
    username: ${DATABASE_USERNAME:postgres}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cooking-advizer}
  jpa:
    generate-ddl: true
